### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by danilovaz** [topaxi/ember-cli-emojione-shim#1]
In README you list this:

```
emojione.shortnameToImage(':smile:')
```

There is others funtions like this?

```
emojione.unicodeToImage(str)
```

**Comment by topaxi** [comment]
I have added a link to the official docs of emojione. I don't think fully copying the whole API here is a good idea, as it might change or add new methods.

**Comment by danilovaz** [comment]
Anyway, this README has a more basic explanation. It would be good explain better. 
For example: in which file I should include import?
